# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import book_pb2 as book__pb2


class BookStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddPerson = channel.unary_unary(
        '/Book/AddPerson',
        request_serializer=book__pb2.Person.SerializeToString,
        response_deserializer=book__pb2.Reply.FromString,
        )
    self.RemovePerson = channel.unary_unary(
        '/Book/RemovePerson',
        request_serializer=book__pb2.Person.SerializeToString,
        response_deserializer=book__pb2.Reply.FromString,
        )
    self.GetListOfPersons = channel.unary_stream(
        '/Book/GetListOfPersons',
        request_serializer=book__pb2.Request.SerializeToString,
        response_deserializer=book__pb2.Person.FromString,
        )


class BookServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddPerson(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemovePerson(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetListOfPersons(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BookServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddPerson': grpc.unary_unary_rpc_method_handler(
          servicer.AddPerson,
          request_deserializer=book__pb2.Person.FromString,
          response_serializer=book__pb2.Reply.SerializeToString,
      ),
      'RemovePerson': grpc.unary_unary_rpc_method_handler(
          servicer.RemovePerson,
          request_deserializer=book__pb2.Person.FromString,
          response_serializer=book__pb2.Reply.SerializeToString,
      ),
      'GetListOfPersons': grpc.unary_stream_rpc_method_handler(
          servicer.GetListOfPersons,
          request_deserializer=book__pb2.Request.FromString,
          response_serializer=book__pb2.Person.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Book', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
